//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SayMore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SayMore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap AudioComponentFileImage {
            get {
                object obj = ResourceManager.GetObject("AudioComponentFileImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AudioFileImage {
            get {
                object obj = ResourceManager.GetObject("AudioFileImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AudioInformedConsent {
            get {
                object obj = ResourceManager.GetObject("AudioInformedConsent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BusyWheelLarge {
            get {
                object obj = ResourceManager.GetObject("BusyWheelLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BusyWheelSmall {
            get {
                object obj = ResourceManager.GetObject("BusyWheelSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ComponentStageColorBlockTemplate {
            get {
                object obj = ResourceManager.GetObject("ComponentStageColorBlockTemplate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ContributorsTabImage {
            get {
                object obj = ResourceManager.GetObject("ContributorsTabImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Copy {
            get {
                object obj = ResourceManager.GetObject("Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DeleteMessageBoxImage {
            get {
                object obj = ResourceManager.GetObject("DeleteMessageBoxImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DropDownArrow {
            get {
                object obj = ResourceManager.GetObject("DropDownArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EventFileImage {
            get {
                object obj = ResourceManager.GetObject("EventFileImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Events {
            get {
                object obj = ResourceManager.GetObject("Events", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Finished {
            get {
                return ResourceManager.GetStream("Finished", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap HSliderThumb {
            get {
                object obj = ResourceManager.GetObject("HSliderThumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HSliderThumbDisabled {
            get {
                object obj = ResourceManager.GetObject("HSliderThumbDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HSliderThumbMousePressed {
            get {
                object obj = ResourceManager.GetObject("HSliderThumbMousePressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageComponentFileImage {
            get {
                object obj = ResourceManager.GetObject("ImageComponentFileImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageFileImage {
            get {
                object obj = ResourceManager.GetObject("ImageFileImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidBrowseForProject {
            get {
                object obj = ResourceManager.GetObject("kimidBrowseForProject", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidChangePicture {
            get {
                object obj = ResourceManager.GetObject("kimidChangePicture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidFemale_NotSelected {
            get {
                object obj = ResourceManager.GetObject("kimidFemale_NotSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidFemale_Selected {
            get {
                object obj = ResourceManager.GetObject("kimidFemale_Selected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidMale_NotSelected {
            get {
                object obj = ResourceManager.GetObject("kimidMale_NotSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidMale_Selected {
            get {
                object obj = ResourceManager.GetObject("kimidMale_Selected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidMoreAction {
            get {
                object obj = ResourceManager.GetObject("kimidMoreAction", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidNewProject {
            get {
                object obj = ResourceManager.GetObject("kimidNewProject", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidNoPhoto {
            get {
                object obj = ResourceManager.GetObject("kimidNoPhoto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidSendReceive {
            get {
                object obj = ResourceManager.GetObject("kimidSendReceive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidWarning {
            get {
                object obj = ResourceManager.GetObject("kimidWarning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LargeSayMoreLogo {
            get {
                object obj = ResourceManager.GetObject("LargeSayMoreLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MuteVolume {
            get {
                object obj = ResourceManager.GetObject("MuteVolume", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NoInformedConsent {
            get {
                object obj = ResourceManager.GetObject("NoInformedConsent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NotesTabImage {
            get {
                object obj = ResourceManager.GetObject("NotesTabImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Overview {
            get {
                object obj = ResourceManager.GetObject("Overview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pause {
            get {
                object obj = ResourceManager.GetObject("Pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap People {
            get {
                object obj = ResourceManager.GetObject("People", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PersonComponentFileImage {
            get {
                object obj = ResourceManager.GetObject("PersonComponentFileImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PersonFileImage {
            get {
                object obj = ResourceManager.GetObject("PersonFileImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Play {
            get {
                object obj = ResourceManager.GetObject("Play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PlayTabImage {
            get {
                object obj = ResourceManager.GetObject("PlayTabImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Print {
            get {
                object obj = ResourceManager.GetObject("Print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Progress {
            get {
                object obj = ResourceManager.GetObject("Progress", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Refresh {
            get {
                object obj = ResourceManager.GetObject("Refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Save {
            get {
                object obj = ResourceManager.GetObject("Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SayMoreText {
            get {
                object obj = ResourceManager.GetObject("SayMoreText", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SendReceive {
            get {
                object obj = ResourceManager.GetObject("SendReceive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmallSayMoreLogo {
            get {
                object obj = ResourceManager.GetObject("SmallSayMoreLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* ---------- Reset default values of Web browsers. ---------- */
        ///* {
        ///	font-size: 100%;
        ///	margin: 0;
        ///	border: 0;
        ///	padding: 0;
        ///}
        ///
        ///table {
        ///	border-spacing: 0; /* Internet Explorer 8 or later. */
        ///	/* For Internet Explorer 7 or earlier, table element has cellspacing attribute. */
        ///}
        ///
        ///body { line-height: 1; }
        ///
        ////* ---------- End of resetting styles ---------- */
        ///
        ///body {
        ///	font-size: 12px;
        ///	font-family: &apos;Segoe UI&apos;, &apos;Tahoma&apos;, &apos;Arial&apos;, &apos;Helvetica&apos;, sans-serif;
        ///}
        ///
        ///h2 {
        ///	margin: 25px 0px 10px 5px;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StatisticsViewStyles {
            get {
                return ResourceManager.GetString("StatisticsViewStyles", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Stop {
            get {
                object obj = ResourceManager.GetObject("Stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TechnicalTabImage {
            get {
                object obj = ResourceManager.GetObject("TechnicalTabImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VideoFileImage {
            get {
                object obj = ResourceManager.GetObject("VideoFileImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VideoInformedConsent {
            get {
                object obj = ResourceManager.GetObject("VideoInformedConsent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ViewTabImage {
            get {
                object obj = ResourceManager.GetObject("ViewTabImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Volume {
            get {
                object obj = ResourceManager.GetObject("Volume", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VSliderThumb {
            get {
                object obj = ResourceManager.GetObject("VSliderThumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VSliderThumbDisabled {
            get {
                object obj = ResourceManager.GetObject("VSliderThumbDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VSliderThumbPressed {
            get {
                object obj = ResourceManager.GetObject("VSliderThumbPressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static object wmpOcxState {
            get {
                object obj = ResourceManager.GetObject("wmpOcxState", resourceCulture);
                return ((object)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WrittenInformedConsent {
            get {
                object obj = ResourceManager.GetObject("WrittenInformedConsent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
