//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SayMore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SayMore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Add {
            get {
                object obj = ResourceManager.GetObject("Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AddBoundary {
            get {
                object obj = ResourceManager.GetObject("AddBoundary", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AudioComponentFileImage {
            get {
                object obj = ResourceManager.GetObject("AudioComponentFileImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AudioFileImage {
            get {
                object obj = ResourceManager.GetObject("AudioFileImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AudioInformedConsent {
            get {
                object obj = ResourceManager.GetObject("AudioInformedConsent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BusyWheelLarge {
            get {
                object obj = ResourceManager.GetObject("BusyWheelLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BusyWheelSmall {
            get {
                object obj = ResourceManager.GetObject("BusyWheelSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CarefulSpeech {
            get {
                object obj = ResourceManager.GetObject("CarefulSpeech", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ColumnChooser {
            get {
                object obj = ResourceManager.GetObject("ColumnChooser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ComponentStageColorBlockTemplate {
            get {
                object obj = ResourceManager.GetObject("ComponentStageColorBlockTemplate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Copy {
            get {
                object obj = ResourceManager.GetObject("Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Delete {
            get {
                object obj = ResourceManager.GetObject("Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DeleteMessageBoxButtonImage {
            get {
                object obj = ResourceManager.GetObject("DeleteMessageBoxButtonImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DeleteMessageBoxImage {
            get {
                object obj = ResourceManager.GetObject("DeleteMessageBoxImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DropDownArrow {
            get {
                object obj = ResourceManager.GetObject("DropDownArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ElanIcon {
            get {
                object obj = ResourceManager.GetObject("ElanIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;&lt;mets ID=&quot;sort-mets_mets&quot; OBJID=&quot;sword-mets&quot; LABEL=&quot;DSpace SWORD Item&quot; PROFILE=&quot;DSpace SIL SIP Profile 1.0&quot; xmlns=&quot;http://www.loc.gov/METS/&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:schemaLocation=&quot;http://www.loc.gov/METS/ http://www.loc.gov/standards/mets/mets.xsd&quot;&gt;
        ///  &lt;metsHdr/&gt;
        ///  &lt;dmdSec ID=&quot;ramp-mets-dmd-2&quot; GROUPID=&quot;ramp-mets-dmd-2_group-1&quot;&gt;
        ///    &lt;mdWrap LABEL=&quot;RAMP Metadata&quot; MDTYPE=&quot;OTHER&quot; OTHERMDTYPE=&quot;S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmptyMets {
            get {
                return ResourceManager.GetString("EmptyMets", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap EventFileImage {
            get {
                object obj = ResourceManager.GetObject("EventFileImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Events {
            get {
                object obj = ResourceManager.GetObject("Events", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Finished {
            get {
                return ResourceManager.GetStream("Finished", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Help {
            get {
                object obj = ResourceManager.GetObject("Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HSliderThumb {
            get {
                object obj = ResourceManager.GetObject("HSliderThumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HSliderThumbDisabled {
            get {
                object obj = ResourceManager.GetObject("HSliderThumbDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HSliderThumbMousePressed {
            get {
                object obj = ResourceManager.GetObject("HSliderThumbMousePressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImageFileImage {
            get {
                object obj = ResourceManager.GetObject("ImageFileImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Information {
            get {
                object obj = ResourceManager.GetObject("Information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InterlinearExport {
            get {
                object obj = ResourceManager.GetObject("InterlinearExport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidBrowseForProject {
            get {
                object obj = ResourceManager.GetObject("kimidBrowseForProject", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidChangePicture {
            get {
                object obj = ResourceManager.GetObject("kimidChangePicture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidFemale_NotSelected {
            get {
                object obj = ResourceManager.GetObject("kimidFemale_NotSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidFemale_Selected {
            get {
                object obj = ResourceManager.GetObject("kimidFemale_Selected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidMale_NotSelected {
            get {
                object obj = ResourceManager.GetObject("kimidMale_NotSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidMale_Selected {
            get {
                object obj = ResourceManager.GetObject("kimidMale_Selected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidMoreAction {
            get {
                object obj = ResourceManager.GetObject("kimidMoreAction", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidNewProject {
            get {
                object obj = ResourceManager.GetObject("kimidNewProject", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidNoPhoto {
            get {
                object obj = ResourceManager.GetObject("kimidNoPhoto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidSendReceive {
            get {
                object obj = ResourceManager.GetObject("kimidSendReceive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidWarning {
            get {
                object obj = ResourceManager.GetObject("kimidWarning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LargeSayMoreLogo {
            get {
                object obj = ResourceManager.GetObject("LargeSayMoreLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ListenToOriginalRecording {
            get {
                object obj = ResourceManager.GetObject("ListenToOriginalRecording", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ListenToOriginalRecordingDown {
            get {
                object obj = ResourceManager.GetObject("ListenToOriginalRecordingDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ListenToSegmentsAnnotation {
            get {
                object obj = ResourceManager.GetObject("ListenToSegmentsAnnotation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MissingAnnotation {
            get {
                object obj = ResourceManager.GetObject("MissingAnnotation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MuteVolume {
            get {
                object obj = ResourceManager.GetObject("MuteVolume", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NoInformedConsent {
            get {
                object obj = ResourceManager.GetObject("NoInformedConsent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NotesTabImage {
            get {
                object obj = ResourceManager.GetObject("NotesTabImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OralTranslation {
            get {
                object obj = ResourceManager.GetObject("OralTranslation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pause {
            get {
                object obj = ResourceManager.GetObject("Pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap People {
            get {
                object obj = ResourceManager.GetObject("People", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PersonFileImage {
            get {
                object obj = ResourceManager.GetObject("PersonFileImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Play {
            get {
                object obj = ResourceManager.GetObject("Play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PlaySegment {
            get {
                object obj = ResourceManager.GetObject("PlaySegment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PlayTabImage {
            get {
                object obj = ResourceManager.GetObject("PlayTabImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Print {
            get {
                object obj = ResourceManager.GetObject("Print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Progress {
            get {
                object obj = ResourceManager.GetObject("Progress", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RampIcon {
            get {
                object obj = ResourceManager.GetObject("RampIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RecordedOralAnnotations {
            get {
                object obj = ResourceManager.GetObject("RecordedOralAnnotations", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RecordErase {
            get {
                object obj = ResourceManager.GetObject("RecordErase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RecordingOralAnnotationInProgress {
            get {
                object obj = ResourceManager.GetObject("RecordingOralAnnotationInProgress", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RecordingPlayback {
            get {
                object obj = ResourceManager.GetObject("RecordingPlayback", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RecordingPlaybackAnnotation {
            get {
                object obj = ResourceManager.GetObject("RecordingPlaybackAnnotation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RecordOralAnnotation {
            get {
                object obj = ResourceManager.GetObject("RecordOralAnnotation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RecordOralAnnotationSmall {
            get {
                object obj = ResourceManager.GetObject("RecordOralAnnotationSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RecordStart {
            get {
                object obj = ResourceManager.GetObject("RecordStart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RecordStop {
            get {
                object obj = ResourceManager.GetObject("RecordStop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Refresh {
            get {
                object obj = ResourceManager.GetObject("Refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RegenerateAnnotationFile {
            get {
                object obj = ResourceManager.GetObject("RegenerateAnnotationFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RerecordOralAnnotation {
            get {
                object obj = ResourceManager.GetObject("RerecordOralAnnotation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Save {
            get {
                object obj = ResourceManager.GetObject("Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SayMoreText {
            get {
                object obj = ResourceManager.GetObject("SayMoreText", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Segment {
            get {
                object obj = ResourceManager.GetObject("Segment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SendReceive {
            get {
                object obj = ResourceManager.GetObject("SendReceive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmallSayMoreLogo {
            get {
                object obj = ResourceManager.GetObject("SmallSayMoreLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* ---------- Reset default values of Web browsers. ---------- */
        ///* {
        ///	font-size: 100%;
        ///	margin: 0;
        ///	border: 0;
        ///	padding: 0;
        ///}
        ///
        ///table {
        ///	border-spacing: 0; /* Internet Explorer 8 or later. */
        ///	/* For Internet Explorer 7 or earlier, table element has cellspacing attribute. */
        ///}
        ///
        ///body { line-height: 1; }
        ///
        ////* ---------- End of resetting styles ---------- */
        ///
        ///body {
        ///	font-size: 12px;
        ///	font-family: &apos;Segoe UI&apos;, &apos;Tahoma&apos;, &apos;Arial&apos;, &apos;Helvetica&apos;, sans-serif;
        ///}
        ///
        ///h2 {
        ///	margin: 25px 0px 10px 5px;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StatisticsViewStyles {
            get {
                return ResourceManager.GetString("StatisticsViewStyles", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap StatusFinished {
            get {
                object obj = ResourceManager.GetObject("StatusFinished", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StatusIn_Progress {
            get {
                object obj = ResourceManager.GetObject("StatusIn_Progress", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StatusIncoming {
            get {
                object obj = ResourceManager.GetObject("StatusIncoming", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StatusSkipped {
            get {
                object obj = ResourceManager.GetObject("StatusSkipped", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Stop {
            get {
                object obj = ResourceManager.GetObject("Stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StopSegment {
            get {
                object obj = ResourceManager.GetObject("StopSegment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TechnicalTabImage {
            get {
                object obj = ResourceManager.GetObject("TechnicalTabImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VideoFileImage {
            get {
                object obj = ResourceManager.GetObject("VideoFileImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VideoInformedConsent {
            get {
                object obj = ResourceManager.GetObject("VideoInformedConsent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Volume {
            get {
                object obj = ResourceManager.GetObject("Volume", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VSliderThumb {
            get {
                object obj = ResourceManager.GetObject("VSliderThumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VSliderThumbDisabled {
            get {
                object obj = ResourceManager.GetObject("VSliderThumbDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VSliderThumbPressed {
            get {
                object obj = ResourceManager.GetObject("VSliderThumbPressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static object wmpOcxState {
            get {
                object obj = ResourceManager.GetObject("wmpOcxState", resourceCulture);
                return ((object)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WrittenInformedConsent {
            get {
                object obj = ResourceManager.GetObject("WrittenInformedConsent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
