//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SayMore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SayMore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap AudioComponentFileImage {
            get {
                object obj = ResourceManager.GetObject("AudioComponentFileImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ContributorsTabImage {
            get {
                object obj = ResourceManager.GetObject("ContributorsTabImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Finished {
            get {
                return ResourceManager.GetStream("Finished", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ImageComponentFileImage {
            get {
                object obj = ResourceManager.GetObject("ImageComponentFileImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidBrowseForProject {
            get {
                object obj = ResourceManager.GetObject("kimidBrowseForProject", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidChangePicture {
            get {
                object obj = ResourceManager.GetObject("kimidChangePicture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidChangeProject {
            get {
                object obj = ResourceManager.GetObject("kimidChangeProject", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidFemale_NotSelected {
            get {
                object obj = ResourceManager.GetObject("kimidFemale_NotSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidFemale_Selected {
            get {
                object obj = ResourceManager.GetObject("kimidFemale_Selected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidMale_NotSelected {
            get {
                object obj = ResourceManager.GetObject("kimidMale_NotSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidMale_Selected {
            get {
                object obj = ResourceManager.GetObject("kimidMale_Selected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidMoreAction {
            get {
                object obj = ResourceManager.GetObject("kimidMoreAction", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidNewProject {
            get {
                object obj = ResourceManager.GetObject("kimidNewProject", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidNoPermissionsWarning {
            get {
                object obj = ResourceManager.GetObject("kimidNoPermissionsWarning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidNoPhoto {
            get {
                object obj = ResourceManager.GetObject("kimidNoPhoto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidOverview {
            get {
                object obj = ResourceManager.GetObject("kimidOverview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidPeople {
            get {
                object obj = ResourceManager.GetObject("kimidPeople", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidSendReceive {
            get {
                object obj = ResourceManager.GetObject("kimidSendReceive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidSessions {
            get {
                object obj = ResourceManager.GetObject("kimidSessions", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidSetup {
            get {
                object obj = ResourceManager.GetObject("kimidSetup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidSpongeText {
            get {
                object obj = ResourceManager.GetObject("kimidSpongeText", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidWarning {
            get {
                object obj = ResourceManager.GetObject("kimidWarning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LargeSayMoreLogo {
            get {
                object obj = ResourceManager.GetObject("LargeSayMoreLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NotesTabImage {
            get {
                object obj = ResourceManager.GetObject("NotesTabImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PersonComponentFileImage {
            get {
                object obj = ResourceManager.GetObject("PersonComponentFileImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PlayTabImage {
            get {
                object obj = ResourceManager.GetObject("PlayTabImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SessionComponentFileImage {
            get {
                object obj = ResourceManager.GetObject("SessionComponentFileImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmallOpenProjectImage {
            get {
                object obj = ResourceManager.GetObject("SmallOpenProjectImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmallOverviewImage {
            get {
                object obj = ResourceManager.GetObject("SmallOverviewImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmallPeopleImage {
            get {
                object obj = ResourceManager.GetObject("SmallPeopleImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmallSayMoreLogo {
            get {
                object obj = ResourceManager.GetObject("SmallSayMoreLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmallSendReceiveImage {
            get {
                object obj = ResourceManager.GetObject("SmallSendReceiveImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmallSessionsImage {
            get {
                object obj = ResourceManager.GetObject("SmallSessionsImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmallSetupImage {
            get {
                object obj = ResourceManager.GetObject("SmallSetupImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TechnicalTabImage {
            get {
                object obj = ResourceManager.GetObject("TechnicalTabImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VideoComponentFileImage {
            get {
                object obj = ResourceManager.GetObject("VideoComponentFileImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ViewTabImage {
            get {
                object obj = ResourceManager.GetObject("ViewTabImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static object wmpOcxState {
            get {
                object obj = ResourceManager.GetObject("wmpOcxState", resourceCulture);
                return ((object)(obj));
            }
        }
    }
}
