//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SayMore.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection MRUList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MRUList"]));
            }
            set {
                this["MRUList"] = value;
            }
        }
        
        /// <summary>
        /// Character used to replace invalid path characters in a person&apos;s name when building a safe name to store in file system.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Character used to replace invalid path characters in a person\'s name when buildin" +
            "g a safe name to store in file system.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_")]
        public char SafeNameReplacementChar {
            get {
                return ((char)(this["SafeNameReplacementChar"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("207, 240, 159")]
        public global::System.Drawing.Color DataEntryPanelColorBegin {
            get {
                return ((global::System.Drawing.Color)(this["DataEntryPanelColorBegin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("169, 219, 168")]
        public global::System.Drawing.Color DataEntryPanelColorEnd {
            get {
                return ((global::System.Drawing.Color)(this["DataEntryPanelColorEnd"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("148, 195, 151")]
        public global::System.Drawing.Color DataEntryPanelColorBorder {
            get {
                return ((global::System.Drawing.Color)(this["DataEntryPanelColorBorder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("196, 209, 227")]
        public global::System.Drawing.Color BarColorBegin {
            get {
                return ((global::System.Drawing.Color)(this["BarColorBegin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("124, 153, 193")]
        public global::System.Drawing.Color BarColorEnd {
            get {
                return ((global::System.Drawing.Color)(this["BarColorEnd"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("83, 110, 145")]
        public global::System.Drawing.Color BarColorBorder {
            get {
                return ((global::System.Drawing.Color)(this["BarColorBorder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int GapBetweenMultimediaObjects {
            get {
                return ((int)(this["GapBetweenMultimediaObjects"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int DefaultHeightOfVideoControl {
            get {
                return ((int)(this["DefaultHeightOfVideoControl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("65")]
        public int DefaultHeightOfAudioControl {
            get {
                return ((int)(this["DefaultHeightOfAudioControl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int DefaultHeightOfImageControl {
            get {
                return ((int)(this["DefaultHeightOfImageControl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RedrawAsMainWndResizes {
            get {
                return ((bool)(this["RedrawAsMainWndResizes"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SIL.Windows.Forms.PortableSettingsProvider.FormSettings NewSessionsFromFilesDlg {
            get {
                return ((global::SIL.Windows.Forms.PortableSettingsProvider.FormSettings)(this["NewSessionsFromFilesDlg"]));
            }
            set {
                this["NewSessionsFromFilesDlg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SIL.Windows.Forms.Widgets.BetterGrid.GridSettings NewSessionsFromFilesDlgComponentGrid {
            get {
                return ((global::SIL.Windows.Forms.Widgets.BetterGrid.GridSettings)(this["NewSessionsFromFilesDlgComponentGrid"]));
            }
            set {
                this["NewSessionsFromFilesDlgComponentGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string NewSessionsFromFilesLastFolder {
            get {
                return ((string)(this["NewSessionsFromFilesLastFolder"]));
            }
            set {
                this["NewSessionsFromFilesLastFolder"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("www.sil.org")]
        public string SilWebSite {
            get {
                return ((string)(this["SilWebSite"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://software.sil.org/saymore/")]
        public string ProgramsWebSite {
            get {
                return ((string)(this["ProgramsWebSite"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int PersonScreenElementListSpiltterPos {
            get {
                return ((int)(this["PersonScreenElementListSpiltterPos"]));
            }
            set {
                this["PersonScreenElementListSpiltterPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int PersonScreenComponentsSplitterPos {
            get {
                return ((int)(this["PersonScreenComponentsSplitterPos"]));
            }
            set {
                this["PersonScreenComponentsSplitterPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int SessionScreenElementsListSplitterPos {
            get {
                return ((int)(this["SessionScreenElementsListSplitterPos"]));
            }
            set {
                this["SessionScreenElementsListSplitterPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int SessionScreenComponentsSplitterPos {
            get {
                return ((int)(this["SessionScreenComponentsSplitterPos"]));
            }
            set {
                this["SessionScreenComponentsSplitterPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SIL.Windows.Forms.PortableSettingsProvider.FormSettings WelcomeDialog {
            get {
                return ((global::SIL.Windows.Forms.PortableSettingsProvider.FormSettings)(this["WelcomeDialog"]));
            }
            set {
                this["WelcomeDialog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SIL.Windows.Forms.PortableSettingsProvider.FormSettings ProjectWindow {
            get {
                return ((global::SIL.Windows.Forms.PortableSettingsProvider.FormSettings)(this["ProjectWindow"]));
            }
            set {
                this["ProjectWindow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SIL.Windows.Forms.Widgets.BetterGrid.GridSettings SessionScreenComponentGrid {
            get {
                return ((global::SIL.Windows.Forms.Widgets.BetterGrid.GridSettings)(this["SessionScreenComponentGrid"]));
            }
            set {
                this["SessionScreenComponentGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SIL.Windows.Forms.Widgets.BetterGrid.GridSettings PersonScreenComponentGrid {
            get {
                return ((global::SIL.Windows.Forms.Widgets.BetterGrid.GridSettings)(this["PersonScreenComponentGrid"]));
            }
            set {
                this["PersonScreenComponentGrid"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool PauseMediaPlayerWhenTabLoosesFocus {
            get {
                return ((bool)(this["PauseMediaPlayerWhenTabLoosesFocus"]));
            }
        }
        
        /// <summary>
        /// These are zoom percentages used when clicking on an image in an image viewer. For each click, the zoom is increased to the next percentage value. When the max value is reached, the zoom percentage changes to the lowest value, etc.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("These are zoom percentages used when clicking on an image in an image viewer. For" +
            " each click, the zoom is increased to the next percentage value. When the max va" +
            "lue is reached, the zoom percentage changes to the lowest value, etc.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25, 50, 75,100, 125, 150, 175, 200, 225, 250, 275, 300")]
        public string ImageViewerClickImageZoomPercentages {
            get {
                return ((string)(this["ImageViewerClickImageZoomPercentages"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>.event</string>
  <string>.person</string>
  <string>.meta</string>
  <string>thumbs.db</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ComponentFileEndingsNotAllowed {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ComponentFileEndingsNotAllowed"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".meta")]
        public string MetadataFileExtension {
            get {
                return ((string)(this["MetadataFileExtension"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".session")]
        public string SessionFileExtension {
            get {
                return ((string)(this["SessionFileExtension"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".person")]
        public string PersonFileExtension {
            get {
                return ((string)(this["PersonFileExtension"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".sprj")]
        public string ProjectFileExtension {
            get {
                return ((string)(this["ProjectFileExtension"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string LastFolderForComponentFileAdd {
            get {
                return ((string)(this["LastFolderForComponentFileAdd"]));
            }
            set {
                this["LastFolderForComponentFileAdd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public float MediaPlayerVolume {
            get {
                return ((float)(this["MediaPlayerVolume"]));
            }
            set {
                this["MediaPlayerVolume"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoPlayMediaPlayerWhenSelectingMediaFile {
            get {
                return ((bool)(this["AutoPlayMediaPlayerWhenSelectingMediaFile"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SIL.Windows.Forms.Widgets.BetterGrid.GridSettings SessionCustomFieldsGrid {
            get {
                return ((global::SIL.Windows.Forms.Widgets.BetterGrid.GridSettings)(this["SessionCustomFieldsGrid"]));
            }
            set {
                this["SessionCustomFieldsGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SIL.Windows.Forms.Widgets.BetterGrid.GridSettings PersonCustomFieldsGrid {
            get {
                return ((global::SIL.Windows.Forms.Widgets.BetterGrid.GridSettings)(this["PersonCustomFieldsGrid"]));
            }
            set {
                this["PersonCustomFieldsGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SIL.Windows.Forms.Widgets.BetterGrid.GridSettings AudioFileFieldsGrid {
            get {
                return ((global::SIL.Windows.Forms.Widgets.BetterGrid.GridSettings)(this["AudioFileFieldsGrid"]));
            }
            set {
                this["AudioFileFieldsGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SIL.Windows.Forms.Widgets.BetterGrid.GridSettings VideoFileFieldsGrid {
            get {
                return ((global::SIL.Windows.Forms.Widgets.BetterGrid.GridSettings)(this["VideoFileFieldsGrid"]));
            }
            set {
                this["VideoFileFieldsGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SIL.Windows.Forms.Widgets.BetterGrid.GridSettings ImageFileFieldsGrid {
            get {
                return ((global::SIL.Windows.Forms.Widgets.BetterGrid.GridSettings)(this["ImageFileFieldsGrid"]));
            }
            set {
                this["ImageFileFieldsGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SIL.Windows.Forms.Widgets.BetterGrid.GridSettings UnknownFileFieldsGrid {
            get {
                return ((global::SIL.Windows.Forms.Widgets.BetterGrid.GridSettings)(this["UnknownFileFieldsGrid"]));
            }
            set {
                this["UnknownFileFieldsGrid"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("207, 240, 159")]
        public global::System.Drawing.Color SessionEditorsBackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["SessionEditorsBackgroundColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("148, 195, 151")]
        public global::System.Drawing.Color SessionEditorsBorderColor {
            get {
                return ((global::System.Drawing.Color)(this["SessionEditorsBorderColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("207, 240, 159")]
        public global::System.Drawing.Color SessionEditorsButtonBackgroundColor1 {
            get {
                return ((global::System.Drawing.Color)(this["SessionEditorsButtonBackgroundColor1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("169, 219, 168")]
        public global::System.Drawing.Color SessionEditorsButtonBackgroundColor2 {
            get {
                return ((global::System.Drawing.Color)(this["SessionEditorsButtonBackgroundColor2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("199, 207, 219")]
        public global::System.Drawing.Color PersonEditorsBackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["PersonEditorsBackgroundColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("112, 146, 190")]
        public global::System.Drawing.Color PersonEditorsBorderColor {
            get {
                return ((global::System.Drawing.Color)(this["PersonEditorsBorderColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("199, 207, 219")]
        public global::System.Drawing.Color PersonEditorsButtonBackgroundColor1 {
            get {
                return ((global::System.Drawing.Color)(this["PersonEditorsButtonBackgroundColor1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("156, 180, 210")]
        public global::System.Drawing.Color PersonEditorsButtonBackgroundColor2 {
            get {
                return ((global::System.Drawing.Color)(this["PersonEditorsButtonBackgroundColor2"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstTimeRun {
            get {
                return ((bool)(this["FirstTimeRun"]));
            }
            set {
                this["FirstTimeRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string DefaultFolderForNewProjects {
            get {
                return ((string)(this["DefaultFolderForNewProjects"]));
            }
            set {
                this["DefaultFolderForNewProjects"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color WorkflowStageTextColor6 {
            get {
                return ((global::System.Drawing.Color)(this["WorkflowStageTextColor6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color WorkflowStageTextColor4 {
            get {
                return ((global::System.Drawing.Color)(this["WorkflowStageTextColor4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color WorkflowStageTextColor5 {
            get {
                return ((global::System.Drawing.Color)(this["WorkflowStageTextColor5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color WorkflowStageTextColor2 {
            get {
                return ((global::System.Drawing.Color)(this["WorkflowStageTextColor2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color WorkflowStageTextColor3 {
            get {
                return ((global::System.Drawing.Color)(this["WorkflowStageTextColor3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color WorkflowStageTextColor1 {
            get {
                return ((global::System.Drawing.Color)(this["WorkflowStageTextColor1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("196, 209, 227")]
        public global::System.Drawing.Color WorkflowStageColor1 {
            get {
                return ((global::System.Drawing.Color)(this["WorkflowStageColor1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("101, 104, 100")]
        public global::System.Drawing.Color WorkflowStageColor2 {
            get {
                return ((global::System.Drawing.Color)(this["WorkflowStageColor2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("207, 240, 159")]
        public global::System.Drawing.Color WorkflowStageColor3 {
            get {
                return ((global::System.Drawing.Color)(this["WorkflowStageColor3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("83, 110, 145")]
        public global::System.Drawing.Color WorkflowStageColor4 {
            get {
                return ((global::System.Drawing.Color)(this["WorkflowStageColor4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("252, 235, 132")]
        public global::System.Drawing.Color WorkflowStageColor5 {
            get {
                return ((global::System.Drawing.Color)(this["WorkflowStageColor5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ivory")]
        public global::System.Drawing.Color IncompleteStageColor {
            get {
                return ((global::System.Drawing.Color)(this["IncompleteStageColor"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SIL.Windows.Forms.Widgets.BetterGrid.GridSettings SessionsListGrid {
            get {
                return ((global::SIL.Windows.Forms.Widgets.BetterGrid.GridSettings)(this["SessionsListGrid"]));
            }
            set {
                this["SessionsListGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SIL.Windows.Forms.Widgets.BetterGrid.GridSettings PersonListGrid {
            get {
                return ((global::SIL.Windows.Forms.Widgets.BetterGrid.GridSettings)(this["PersonListGrid"]));
            }
            set {
                this["PersonListGrid"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("252, 235, 132")]
        public global::System.Drawing.Color IncomingStatusColor {
            get {
                return ((global::System.Drawing.Color)(this["IncomingStatusColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("124, 153, 193")]
        public global::System.Drawing.Color In_ProgressStatusColor {
            get {
                return ((global::System.Drawing.Color)(this["In_ProgressStatusColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("169, 219, 168")]
        public global::System.Drawing.Color FinishedStatusColor {
            get {
                return ((global::System.Drawing.Color)(this["FinishedStatusColor"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool AllowStatisticsChartLabelsToWrap {
            get {
                return ((bool)(this["AllowStatisticsChartLabelsToWrap"]));
            }
            set {
                this["AllowStatisticsChartLabelsToWrap"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("148, 195, 151")]
        public global::System.Drawing.Color WorkflowStageColor6 {
            get {
                return ((global::System.Drawing.Color)(this["WorkflowStageColor6"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SIL.Windows.Forms.Widgets.BetterGrid.GridSettings ContributorsGrid {
            get {
                return ((global::SIL.Windows.Forms.Widgets.BetterGrid.GridSettings)(this["ContributorsGrid"]));
            }
            set {
                this["ContributorsGrid"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("252, 235, 132")]
        public global::System.Drawing.Color MissingDataWindowColor {
            get {
                return ((global::System.Drawing.Color)(this["MissingDataWindowColor"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NeedUpgrade {
            get {
                return ((bool)(this["NeedUpgrade"]));
            }
            set {
                this["NeedUpgrade"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("htm;html;xml;txt;pdf")]
        public string FileTypesToAllowLoadingInBrowserEditor {
            get {
                return ((string)(this["FileTypesToAllowLoadingInBrowserEditor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("author;compiler;consultant;developer;editor;facilitator;illustrator;interviewer;p" +
            "hotographer;recorder;researcher;signer;speaker;transcriber;translator")]
        public string RampContributorRoles {
            get {
                return ((string)(this["RampContributorRoles"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SIL.Windows.Forms.PortableSettingsProvider.FormSettings ArchivingDialog {
            get {
                return ((global::SIL.Windows.Forms.PortableSettingsProvider.FormSettings)(this["ArchivingDialog"]));
            }
            set {
                this["ArchivingDialog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SIL.Windows.Forms.Widgets.BetterGrid.GridSettings SegmentGrid {
            get {
                return ((global::SIL.Windows.Forms.Widgets.BetterGrid.GridSettings)(this["SegmentGrid"]));
            }
            set {
                this["SegmentGrid"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".eaf")]
        public string AnnotationFileExtension {
            get {
                return ((string)(this["AnnotationFileExtension"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AnnotationEditorPlaybackSpeedIndex {
            get {
                return ((int)(this["AnnotationEditorPlaybackSpeedIndex"]));
            }
            set {
                this["AnnotationEditorPlaybackSpeedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.75")]
        public decimal AnnotationEditorVideoWindowYtoXRatio {
            get {
                return ((decimal)(this["AnnotationEditorVideoWindowYtoXRatio"]));
            }
            set {
                this["AnnotationEditorVideoWindowYtoXRatio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int AnnotationEditorSpiltterPos {
            get {
                return ((int)(this["AnnotationEditorSpiltterPos"]));
            }
            set {
                this["AnnotationEditorSpiltterPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string TranscriptionWsForFWInterlinearExport {
            get {
                return ((string)(this["TranscriptionWsForFWInterlinearExport"]));
            }
            set {
                this["TranscriptionWsForFWInterlinearExport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string FreeTranslationWsForFWInterlinearExport {
            get {
                return ((string)(this["FreeTranslationWsForFWInterlinearExport"]));
            }
            set {
                this["FreeTranslationWsForFWInterlinearExport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SIL.Windows.Forms.PortableSettingsProvider.FormSettings OralAnnotationRecorderDlg {
            get {
                return ((global::SIL.Windows.Forms.PortableSettingsProvider.FormSettings)(this["OralAnnotationRecorderDlg"]));
            }
            set {
                this["OralAnnotationRecorderDlg"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".oralAnnotations.wav")]
        public string OralAnnotationGeneratedFileSuffix {
            get {
                return ((string)(this["OralAnnotationGeneratedFileSuffix"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_Annotations")]
        public string OralAnnotationsFolderSuffix {
            get {
                return ((string)(this["OralAnnotationsFolderSuffix"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_Careful.wav")]
        public string OralAnnotationCarefulSegmentFileSuffix {
            get {
                return ((string)(this["OralAnnotationCarefulSegmentFileSuffix"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_Translation.wav")]
        public string OralAnnotationTranslationSegmentFileSuffix {
            get {
                return ((string)(this["OralAnnotationTranslationSegmentFileSuffix"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int MillisecondsToAdvanceSegmentBoundaryOnRightArrow {
            get {
                return ((int)(this["MillisecondsToAdvanceSegmentBoundaryOnRightArrow"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int MillisecondsToBackupSegmentBoundaryOnLeftArrow {
            get {
                return ((int)(this["MillisecondsToBackupSegmentBoundaryOnLeftArrow"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int MillisecondsToRePlayAfterAdjustingSegmentBoundary {
            get {
                return ((int)(this["MillisecondsToRePlayAfterAdjustingSegmentBoundary"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en")]
        public string UserInterfaceLanguage {
            get {
                return ((string)(this["UserInterfaceLanguage"]));
            }
            set {
                this["UserInterfaceLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string LocalizationDlgSettings {
            get {
                return ((string)(this["LocalizationDlgSettings"]));
            }
            set {
                this["LocalizationDlgSettings"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public int MillisecondsToDelayPlaybackAfterAdjustingSegmentBoundary {
            get {
                return ((int)(this["MillisecondsToDelayPlaybackAfterAdjustingSegmentBoundary"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public float ZoomPercentageInAnnotationRecordingDlg {
            get {
                return ((float)(this["ZoomPercentageInAnnotationRecordingDlg"]));
            }
            set {
                this["ZoomPercentageInAnnotationRecordingDlg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SIL.Windows.Forms.PortableSettingsProvider.FormSettings ManualSegmenterDlg {
            get {
                return ((global::SIL.Windows.Forms.PortableSettingsProvider.FormSettings)(this["ManualSegmenterDlg"]));
            }
            set {
                this["ManualSegmenterDlg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public float ZoomPercentageInManualSegmenterDlg {
            get {
                return ((float)(this["ZoomPercentageInManualSegmenterDlg"]));
            }
            set {
                this["ZoomPercentageInManualSegmenterDlg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int DefaultSegmentationMethod {
            get {
                return ((int)(this["DefaultSegmentationMethod"]));
            }
            set {
                this["DefaultSegmentationMethod"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("460")]
        public int MinimumAnnotationSegmentLengthInMilliseconds {
            get {
                return ((int)(this["MinimumAnnotationSegmentLengthInMilliseconds"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SIL.Windows.Forms.PortableSettingsProvider.FormSettings SessionRecorderDlg {
            get {
                return ((global::SIL.Windows.Forms.PortableSettingsProvider.FormSettings)(this["SessionRecorderDlg"]));
            }
            set {
                this["SessionRecorderDlg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int TranscriptionPlaybackType {
            get {
                return ((int)(this["TranscriptionPlaybackType"]));
            }
            set {
                this["TranscriptionPlaybackType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int TranslationPlaybackType {
            get {
                return ((int)(this["TranslationPlaybackType"]));
            }
            set {
                this["TranslationPlaybackType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SIL.Windows.Forms.PortableSettingsProvider.FormSettings MPlayerDebuggingOutputWindow {
            get {
                return ((global::SIL.Windows.Forms.PortableSettingsProvider.FormSettings)(this["MPlayerDebuggingOutputWindow"]));
            }
            set {
                this["MPlayerDebuggingOutputWindow"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_StandardAudio.wav")]
        public string StandardAudioFileSuffix {
            get {
                return ((string)(this["StandardAudioFileSuffix"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int SegmentingWaveViewPixelsPerSecond {
            get {
                return ((int)(this["SegmentingWaveViewPixelsPerSecond"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool PreventSegmentBoundaryMovingWhereTextAnnotationsAreAdjacent {
            get {
                return ((bool)(this["PreventSegmentBoundaryMovingWhereTextAnnotationsAreAdjacent"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("460")]
        public int MinimumSegmentLengthInMilliseconds {
            get {
                return ((int)(this["MinimumSegmentLengthInMilliseconds"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SIL.Windows.Forms.PortableSettingsProvider.FormSettings ConvertMediaDlg {
            get {
                return ((global::SIL.Windows.Forms.PortableSettingsProvider.FormSettings)(this["ConvertMediaDlg"]));
            }
            set {
                this["ConvertMediaDlg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool ShowFFmpegDetailsWhenConvertingMedia {
            get {
                return ((bool)(this["ShowFFmpegDetailsWhenConvertingMedia"]));
            }
            set {
                this["ShowFFmpegDetailsWhenConvertingMedia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SIL.Windows.Forms.PortableSettingsProvider.FormSettings MediaFileMoreInfoDlg {
            get {
                return ((global::SIL.Windows.Forms.PortableSettingsProvider.FormSettings)(this["MediaFileMoreInfoDlg"]));
            }
            set {
                this["MediaFileMoreInfoDlg"] = value;
            }
        }
        
        /// <summary>
        /// The auto-segmenter will calculate the &quot;optimal&quot; segment length to be halfway between AutoSegmenterMinimumSegmentLengthInMilliseconds and this value.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Configuration.SettingsDescriptionAttribute("The auto-segmenter will calculate the \"optimal\" segment length to be halfway betw" +
            "een AutoSegmenterMinimumSegmentLengthInMilliseconds and this value.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public int DefaultAutoSegmenterMaximumSegmentLengthInMilliseconds {
            get {
                return ((int)(this["DefaultAutoSegmenterMaximumSegmentLengthInMilliseconds"]));
            }
        }
        
        /// <summary>
        /// The larger this value, the longer the pause that the auto-segmenter will try to find to use as a break.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Configuration.SettingsDescriptionAttribute("The larger this value, the longer the pause that the auto-segmenter will try to f" +
            "ind to use as a break.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public int DefaultAutoSegmenterPreferrerdPauseLengthInMilliseconds {
            get {
                return ((int)(this["DefaultAutoSegmenterPreferrerdPauseLengthInMilliseconds"]));
            }
        }
        
        /// <summary>
        /// The larger this number, the more strongly the auto-segmenter will favor possible breaks close to the midpoint between the minimum and the maximum segment length.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Configuration.SettingsDescriptionAttribute("The larger this number, the more strongly the auto-segmenter will favor possible " +
            "breaks close to the midpoint between the minimum and the maximum segment length." +
            "")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4E-06")]
        public double DefaultAutoSegmenterOptimumLengthClampingFactor {
            get {
                return ((double)(this["DefaultAutoSegmenterOptimumLengthClampingFactor"]));
            }
        }
        
        /// <summary>
        /// The auto-segmenter will calculate the &quot;optimal&quot; segment length to be halfway between this value and AutoSegmenterMaximumSegmentLengthInMilliseconds.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Configuration.SettingsDescriptionAttribute("The auto-segmenter will calculate the \"optimal\" segment length to be halfway betw" +
            "een this value and AutoSegmenterMaximumSegmentLengthInMilliseconds.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int DefaultAutoSegmenterMinimumSegmentLengthInMilliseconds {
            get {
                return ((int)(this["DefaultAutoSegmenterMinimumSegmentLengthInMilliseconds"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arbil\\arbil-stable.exe")]
        public string ProgramToLaunchForIMDIPackage {
            get {
                return ((string)(this["ProgramToLaunchForIMDIPackage"]));
            }
            set {
                this["ProgramToLaunchForIMDIPackage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200,120,80,200")]
        public string PersonContributionColumns {
            get {
                return ((string)(this["PersonContributionColumns"]));
            }
            set {
                this["PersonContributionColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SIL.Windows.Forms.Widgets.BetterGrid.GridSettings ProjectDescriptionDocumentsComponentGrid {
            get {
                return ((global::SIL.Windows.Forms.Widgets.BetterGrid.GridSettings)(this["ProjectDescriptionDocumentsComponentGrid"]));
            }
            set {
                this["ProjectDescriptionDocumentsComponentGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SIL.Windows.Forms.PortableSettingsProvider.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SIL.Windows.Forms.Widgets.BetterGrid.GridSettings ProjectOtherDocumentsComponentGrid {
            get {
                return ((global::SIL.Windows.Forms.Widgets.BetterGrid.GridSettings)(this["ProjectOtherDocumentsComponentGrid"]));
            }
            set {
                this["ProjectOtherDocumentsComponentGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastExportDestinationFolder {
            get {
                return ((string)(this["LastExportDestinationFolder"]));
            }
            set {
                this["LastExportDestinationFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastToolboxExportDestinationFolder {
            get {
                return ((string)(this["LastToolboxExportDestinationFolder"]));
            }
            set {
                this["LastToolboxExportDestinationFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastAudacityExportDestinationFolder {
            get {
                return ((string)(this["LastAudacityExportDestinationFolder"]));
            }
            set {
                this["LastAudacityExportDestinationFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastFlexInterlinearExportDestinationFolder {
            get {
                return ((string)(this["LastFlexInterlinearExportDestinationFolder"]));
            }
            set {
                this["LastFlexInterlinearExportDestinationFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Interactivity|Planning Type|Task")]
        public string AdditionalFieldsToHide {
            get {
                return ((string)(this["AdditionalFieldsToHide"]));
            }
            set {
                this["AdditionalFieldsToHide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LoadComponentFileIcons {
            get {
                return ((bool)(this["LoadComponentFileIcons"]));
            }
            set {
                this["LoadComponentFileIcons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastOralTranslationExportDestinationFolder {
            get {
                return ((string)(this["LastOralTranslationExportDestinationFolder"]));
            }
            set {
                this["LastOralTranslationExportDestinationFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastCarefulSpeechExportDestinationFolder {
            get {
                return ((string)(this["LastCarefulSpeechExportDestinationFolder"]));
            }
            set {
                this["LastCarefulSpeechExportDestinationFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SIL.Windows.Forms.PortableSettingsProvider.FormSettings ExportMediaDlg {
            get {
                return ((global::SIL.Windows.Forms.PortableSettingsProvider.FormSettings)(this["ExportMediaDlg"]));
            }
            set {
                this["ExportMediaDlg"] = value;
            }
        }
    }
}
