//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SayMore.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection MRUList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MRUList"]));
            }
            set {
                this["MRUList"] = value;
            }
        }
        
        /// <summary>
        /// Character used to replace invalid path characters in a person&apos;s name when building a safe name to store in file system.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Character used to replace invalid path characters in a person\'s name when buildin" +
            "g a safe name to store in file system.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_")]
        public char SafeNameReplacementChar {
            get {
                return ((char)(this["SafeNameReplacementChar"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("207, 240, 159")]
        public global::System.Drawing.Color DataEntryPanelColorBegin {
            get {
                return ((global::System.Drawing.Color)(this["DataEntryPanelColorBegin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("169, 219, 168")]
        public global::System.Drawing.Color DataEntryPanelColorEnd {
            get {
                return ((global::System.Drawing.Color)(this["DataEntryPanelColorEnd"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("148, 195, 151")]
        public global::System.Drawing.Color DataEntryPanelColorBorder {
            get {
                return ((global::System.Drawing.Color)(this["DataEntryPanelColorBorder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("196, 209, 227")]
        public global::System.Drawing.Color BarColorBegin {
            get {
                return ((global::System.Drawing.Color)(this["BarColorBegin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("124, 153, 193")]
        public global::System.Drawing.Color BarColorEnd {
            get {
                return ((global::System.Drawing.Color)(this["BarColorEnd"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("83, 110, 145")]
        public global::System.Drawing.Color BarColorBorder {
            get {
                return ((global::System.Drawing.Color)(this["BarColorBorder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int GapBetweenMultimediaObjects {
            get {
                return ((int)(this["GapBetweenMultimediaObjects"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int DefaultHeightOfVideoControl {
            get {
                return ((int)(this["DefaultHeightOfVideoControl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("65")]
        public int DefaultHeightOfAudioControl {
            get {
                return ((int)(this["DefaultHeightOfAudioControl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int DefaultHeightOfImageControl {
            get {
                return ((int)(this["DefaultHeightOfImageControl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>.mp3</string>
  <string>.wav</string>
  <string>.wma</string>
  <string>.acc</string>
  <string>.ogg</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection AudioFileExtensions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AudioFileExtensions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>.wmv</string>
  <string>.avi</string>
  <string>.mpg</string>
  <string>.mpeg</string>
  <string>.mpa</string>
  <string>.asf</string>
  <string>.mov</string>
  <string>.mp4</string>
  <string>.mts</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection VideoFileExtensions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["VideoFileExtensions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>.jpg</string>
  <string>.jpeg</string>
  <string>.gif</string>
  <string>.tif</string>
  <string>.png</string>
  <string>.bmp</string>
  <string>.dib</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ImageFileExtensions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ImageFileExtensions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RedrawAsMainWndResizes {
            get {
                return ((bool)(this["RedrawAsMainWndResizes"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilTools.FormSettings NewEventsFromFilesDlg {
            get {
                return ((global::SilTools.FormSettings)(this["NewEventsFromFilesDlg"]));
            }
            set {
                this["NewEventsFromFilesDlg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilTools.GridSettings NewEventsFromFilesDlgComponentGrid {
            get {
                return ((global::SilTools.GridSettings)(this["NewEventsFromFilesDlgComponentGrid"]));
            }
            set {
                this["NewEventsFromFilesDlgComponentGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string NewEventsFromFilesLastFolder {
            get {
                return ((string)(this["NewEventsFromFilesLastFolder"]));
            }
            set {
                this["NewEventsFromFilesLastFolder"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("www.sil.org")]
        public string SilWebSite {
            get {
                return ((string)(this["SilWebSite"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://saymore.palaso.org/")]
        public string ProgramsWebSite {
            get {
                return ((string)(this["ProgramsWebSite"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int PersonScreenElementListSpiltterPos {
            get {
                return ((int)(this["PersonScreenElementListSpiltterPos"]));
            }
            set {
                this["PersonScreenElementListSpiltterPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int PersonScreenComponentsSplitterPos {
            get {
                return ((int)(this["PersonScreenComponentsSplitterPos"]));
            }
            set {
                this["PersonScreenComponentsSplitterPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int EventScreenElementsListSplitterPos {
            get {
                return ((int)(this["EventScreenElementsListSplitterPos"]));
            }
            set {
                this["EventScreenElementsListSplitterPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int EventScreenComponentsSplitterPos {
            get {
                return ((int)(this["EventScreenComponentsSplitterPos"]));
            }
            set {
                this["EventScreenComponentsSplitterPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilTools.FormSettings WelcomeDialog {
            get {
                return ((global::SilTools.FormSettings)(this["WelcomeDialog"]));
            }
            set {
                this["WelcomeDialog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilTools.FormSettings ProjectWindow {
            get {
                return ((global::SilTools.FormSettings)(this["ProjectWindow"]));
            }
            set {
                this["ProjectWindow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilTools.GridSettings EventScreenComponentGrid {
            get {
                return ((global::SilTools.GridSettings)(this["EventScreenComponentGrid"]));
            }
            set {
                this["EventScreenComponentGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilTools.GridSettings PersonScreenComponentGrid {
            get {
                return ((global::SilTools.GridSettings)(this["PersonScreenComponentGrid"]));
            }
            set {
                this["PersonScreenComponentGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool PauseMediaPlayerWhenTabLoosesFocus {
            get {
                return ((bool)(this["PauseMediaPlayerWhenTabLoosesFocus"]));
            }
            set {
                this["PauseMediaPlayerWhenTabLoosesFocus"] = value;
            }
        }
        
        /// <summary>
        /// These are zoom percentages used when clicking on an image in an image viewer. For each click, the zoom is increased to the next percentage value. When the max value is reached, the zoom percentage changes to the lowest value, etc.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("These are zoom percentages used when clicking on an image in an image viewer. For" +
            " each click, the zoom is increased to the next percentage value. When the max va" +
            "lue is reached, the zoom percentage changes to the lowest value, etc.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25, 50, 75,100, 125, 150, 175, 200, 225, 250, 275, 300")]
        public string ImageViewerClickImageZoomPercentages {
            get {
                return ((string)(this["ImageViewerClickImageZoomPercentages"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>.event</string>
  <string>.person</string>
  <string>.meta</string>
  <string>thumbs.db</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ComponentFileEndingsNotAllowed {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ComponentFileEndingsNotAllowed"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".meta")]
        public string MetadataFileExtension {
            get {
                return ((string)(this["MetadataFileExtension"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".event")]
        public string EventFileExtension {
            get {
                return ((string)(this["EventFileExtension"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".person")]
        public string PersonFileExtension {
            get {
                return ((string)(this["PersonFileExtension"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".sprj")]
        public string ProjectFileExtension {
            get {
                return ((string)(this["ProjectFileExtension"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string LastFolderForComponentFileAdd {
            get {
                return ((string)(this["LastFolderForComponentFileAdd"]));
            }
            set {
                this["LastFolderForComponentFileAdd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public float MediaPlayerVolume {
            get {
                return ((float)(this["MediaPlayerVolume"]));
            }
            set {
                this["MediaPlayerVolume"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoPlayMediaPlayerWhenSelectingMediaFile {
            get {
                return ((bool)(this["AutoPlayMediaPlayerWhenSelectingMediaFile"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection CustomEventFileFields {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CustomEventFileFields"]));
            }
            set {
                this["CustomEventFileFields"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection CustomPersonFileFields {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CustomPersonFileFields"]));
            }
            set {
                this["CustomPersonFileFields"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection CustomImageFileFields {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CustomImageFileFields"]));
            }
            set {
                this["CustomImageFileFields"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection CustomAudioFileFields {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CustomAudioFileFields"]));
            }
            set {
                this["CustomAudioFileFields"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection CustomVideoFileFields {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CustomVideoFileFields"]));
            }
            set {
                this["CustomVideoFileFields"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection CustomUnknownFileFields {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CustomUnknownFileFields"]));
            }
            set {
                this["CustomUnknownFileFields"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilTools.GridSettings EventCustomFieldsGrid {
            get {
                return ((global::SilTools.GridSettings)(this["EventCustomFieldsGrid"]));
            }
            set {
                this["EventCustomFieldsGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilTools.GridSettings PersonCustomFieldsGrid {
            get {
                return ((global::SilTools.GridSettings)(this["PersonCustomFieldsGrid"]));
            }
            set {
                this["PersonCustomFieldsGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilTools.GridSettings AudioFileFieldsGrid {
            get {
                return ((global::SilTools.GridSettings)(this["AudioFileFieldsGrid"]));
            }
            set {
                this["AudioFileFieldsGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilTools.GridSettings VideoFileFieldsGrid {
            get {
                return ((global::SilTools.GridSettings)(this["VideoFileFieldsGrid"]));
            }
            set {
                this["VideoFileFieldsGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilTools.GridSettings ImageFileFieldsGrid {
            get {
                return ((global::SilTools.GridSettings)(this["ImageFileFieldsGrid"]));
            }
            set {
                this["ImageFileFieldsGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilTools.GridSettings UnknownFileFieldsGrid {
            get {
                return ((global::SilTools.GridSettings)(this["UnknownFileFieldsGrid"]));
            }
            set {
                this["UnknownFileFieldsGrid"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("207, 240, 159")]
        public global::System.Drawing.Color EventEditorsBackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["EventEditorsBackgroundColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("148, 195, 151")]
        public global::System.Drawing.Color EventEditorsBorderColor {
            get {
                return ((global::System.Drawing.Color)(this["EventEditorsBorderColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("207, 240, 159")]
        public global::System.Drawing.Color EventEditorsButtonBackgroundColor1 {
            get {
                return ((global::System.Drawing.Color)(this["EventEditorsButtonBackgroundColor1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("169, 219, 168")]
        public global::System.Drawing.Color EventEditorsButtonBackgroundColor2 {
            get {
                return ((global::System.Drawing.Color)(this["EventEditorsButtonBackgroundColor2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("199, 207, 219")]
        public global::System.Drawing.Color PersonEditorsBackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["PersonEditorsBackgroundColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("112, 146, 190")]
        public global::System.Drawing.Color PersonEditorsBorderColor {
            get {
                return ((global::System.Drawing.Color)(this["PersonEditorsBorderColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("199, 207, 219")]
        public global::System.Drawing.Color PersonEditorsButtonBackgroundColor1 {
            get {
                return ((global::System.Drawing.Color)(this["PersonEditorsButtonBackgroundColor1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("156, 180, 210")]
        public global::System.Drawing.Color PersonEditorsButtonBackgroundColor2 {
            get {
                return ((global::System.Drawing.Color)(this["PersonEditorsButtonBackgroundColor2"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstTimeRun {
            get {
                return ((bool)(this["FirstTimeRun"]));
            }
            set {
                this["FirstTimeRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string DefaultFolderForNewProjects {
            get {
                return ((string)(this["DefaultFolderForNewProjects"]));
            }
            set {
                this["DefaultFolderForNewProjects"] = value;
            }
        }
        
        /// <summary>
        /// This is used for tests and prevents the display of the confirmation dialog box when moving deleted session and persons to the recycle bin.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Configuration.SettingsDescriptionAttribute("This is used for tests and prevents the display of the confirmation dialog box wh" +
            "en moving deleted session and persons to the recycle bin.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PreventDeleteElementSystemConfirmationMessage {
            get {
                return ((bool)(this["PreventDeleteElementSystemConfirmationMessage"]));
            }
            set {
                this["PreventDeleteElementSystemConfirmationMessage"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color WorkflowStageTextColor6 {
            get {
                return ((global::System.Drawing.Color)(this["WorkflowStageTextColor6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color WorkflowStageTextColor4 {
            get {
                return ((global::System.Drawing.Color)(this["WorkflowStageTextColor4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color WorkflowStageTextColor5 {
            get {
                return ((global::System.Drawing.Color)(this["WorkflowStageTextColor5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color WorkflowStageTextColor2 {
            get {
                return ((global::System.Drawing.Color)(this["WorkflowStageTextColor2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color WorkflowStageTextColor3 {
            get {
                return ((global::System.Drawing.Color)(this["WorkflowStageTextColor3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color WorkflowStageTextColor1 {
            get {
                return ((global::System.Drawing.Color)(this["WorkflowStageTextColor1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("196, 209, 227")]
        public global::System.Drawing.Color WorkflowStageColor1 {
            get {
                return ((global::System.Drawing.Color)(this["WorkflowStageColor1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("101, 104, 100")]
        public global::System.Drawing.Color WorkflowStageColor2 {
            get {
                return ((global::System.Drawing.Color)(this["WorkflowStageColor2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("207, 240, 159")]
        public global::System.Drawing.Color WorkflowStageColor3 {
            get {
                return ((global::System.Drawing.Color)(this["WorkflowStageColor3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("83, 110, 145")]
        public global::System.Drawing.Color WorkflowStageColor4 {
            get {
                return ((global::System.Drawing.Color)(this["WorkflowStageColor4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("252, 235, 132")]
        public global::System.Drawing.Color WorkflowStageColor5 {
            get {
                return ((global::System.Drawing.Color)(this["WorkflowStageColor5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ivory")]
        public global::System.Drawing.Color IncompleteStageColor {
            get {
                return ((global::System.Drawing.Color)(this["IncompleteStageColor"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilTools.GridSettings EventsListGrid {
            get {
                return ((global::SilTools.GridSettings)(this["EventsListGrid"]));
            }
            set {
                this["EventsListGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilTools.GridSettings PersonListGrid {
            get {
                return ((global::SilTools.GridSettings)(this["PersonListGrid"]));
            }
            set {
                this["PersonListGrid"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("252, 235, 132")]
        public global::System.Drawing.Color IncomingStatusColor {
            get {
                return ((global::System.Drawing.Color)(this["IncomingStatusColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("124, 153, 193")]
        public global::System.Drawing.Color In_ProgressStatusColor {
            get {
                return ((global::System.Drawing.Color)(this["In_ProgressStatusColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("169, 219, 168")]
        public global::System.Drawing.Color FinishedStatusColor {
            get {
                return ((global::System.Drawing.Color)(this["FinishedStatusColor"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool AllowStatisticsChartLabelsToWrap {
            get {
                return ((bool)(this["AllowStatisticsChartLabelsToWrap"]));
            }
            set {
                this["AllowStatisticsChartLabelsToWrap"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("148, 195, 151")]
        public global::System.Drawing.Color WorkflowStageColor6 {
            get {
                return ((global::System.Drawing.Color)(this["WorkflowStageColor6"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilTools.GridSettings ContributorsGrid {
            get {
                return ((global::SilTools.GridSettings)(this["ContributorsGrid"]));
            }
            set {
                this["ContributorsGrid"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("252, 235, 132")]
        public global::System.Drawing.Color MissingDataWindowColor {
            get {
                return ((global::System.Drawing.Color)(this["MissingDataWindowColor"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NeedUpgrade {
            get {
                return ((bool)(this["NeedUpgrade"]));
            }
            set {
                this["NeedUpgrade"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Palaso.Reporting.ReportingSettings Reporting {
            get {
                return ((global::Palaso.Reporting.ReportingSettings)(this["Reporting"]));
            }
            set {
                this["Reporting"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".doc;.odt;.ppt;.xls")]
        public string FileTypesToAvoidLoadingInBrowserEditor {
            get {
                return ((string)(this["FileTypesToAvoidLoadingInBrowserEditor"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.help.insitehome.org/reap/manual/ramp-users-manual")]
        public string RampWebSite {
            get {
                return ((string)(this["RampWebSite"]));
            }
            set {
                this["RampWebSite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("author;compiler;consultant;developer;editor;facilitator;illustrator;interviewer;p" +
            "hotographer;recorder;researcher;signer;speaker;transcriber;translator")]
        public string RampContributorRoles {
            get {
                return ((string)(this["RampContributorRoles"]));
            }
            set {
                this["RampContributorRoles"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("original")]
        public string OriginalRecordingComponentRoleId {
            get {
                return ((string)(this["OriginalRecordingComponentRoleId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>.txt</string>
  <string>.doc</string>
  <string>.docx</string>
  <string>.odt</string>
  <string>.rtf</string>
  <string>.htm</string>
  <string>.html</string>
  <string>.pdf</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection TextFileExtensions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TextFileExtensions"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilTools.FormSettings ArchivingDialog {
            get {
                return ((global::SilTools.FormSettings)(this["ArchivingDialog"]));
            }
            set {
                this["ArchivingDialog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilTools.GridSettings SegmentGrid {
            get {
                return ((global::SilTools.GridSettings)(this["SegmentGrid"]));
            }
            set {
                this["SegmentGrid"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".eaf")]
        public string AnnotationFileExtension {
            get {
                return ((string)(this["AnnotationFileExtension"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AnnotationEditorPlaybackSpeedIndex {
            get {
                return ((int)(this["AnnotationEditorPlaybackSpeedIndex"]));
            }
            set {
                this["AnnotationEditorPlaybackSpeedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.75")]
        public decimal AnnotationEditorVideoWindowYtoXRatio {
            get {
                return ((decimal)(this["AnnotationEditorVideoWindowYtoXRatio"]));
            }
            set {
                this["AnnotationEditorVideoWindowYtoXRatio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int AnnotationEditorSpiltterPos {
            get {
                return ((int)(this["AnnotationEditorSpiltterPos"]));
            }
            set {
                this["AnnotationEditorSpiltterPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string TranscriptionWsForFWInterlinearExport {
            get {
                return ((string)(this["TranscriptionWsForFWInterlinearExport"]));
            }
            set {
                this["TranscriptionWsForFWInterlinearExport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string FreeTranslationWsForFWInterlinearExport {
            get {
                return ((string)(this["FreeTranslationWsForFWInterlinearExport"]));
            }
            set {
                this["FreeTranslationWsForFWInterlinearExport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilTools.FormSettings OralAnnotationRecorderDlg {
            get {
                return ((global::SilTools.FormSettings)(this["OralAnnotationRecorderDlg"]));
            }
            set {
                this["OralAnnotationRecorderDlg"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".oralAnnotations.wav")]
        public string OralAnnotationGeneratedFileAffix {
            get {
                return ((string)(this["OralAnnotationGeneratedFileAffix"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_Annotations")]
        public string OralAnnotationsFolderAffix {
            get {
                return ((string)(this["OralAnnotationsFolderAffix"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_Careful.wav")]
        public string OralAnnotationCarefulSegmentFileAffix {
            get {
                return ((string)(this["OralAnnotationCarefulSegmentFileAffix"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_Translation.wav")]
        public string OralAnnotationTranslationSegmentFileAffix {
            get {
                return ((string)(this["OralAnnotationTranslationSegmentFileAffix"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}_to_{1}{2}")]
        public string OralAnnotationSegmentFileFormat {
            get {
                return ((string)(this["OralAnnotationSegmentFileFormat"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int MillisecondsToAdvanceSegmentBoundaryOnRightArrow {
            get {
                return ((int)(this["MillisecondsToAdvanceSegmentBoundaryOnRightArrow"]));
            }
            set {
                this["MillisecondsToAdvanceSegmentBoundaryOnRightArrow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int MillisecondsToBackupSegmentBoundaryOnLeftArrow {
            get {
                return ((int)(this["MillisecondsToBackupSegmentBoundaryOnLeftArrow"]));
            }
            set {
                this["MillisecondsToBackupSegmentBoundaryOnLeftArrow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int MillisecondsToRePlayAfterAdjustingSegmentBoundary {
            get {
                return ((int)(this["MillisecondsToRePlayAfterAdjustingSegmentBoundary"]));
            }
            set {
                this["MillisecondsToRePlayAfterAdjustingSegmentBoundary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en")]
        public string UserInterfaceLanguage {
            get {
                return ((string)(this["UserInterfaceLanguage"]));
            }
            set {
                this["UserInterfaceLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string LocalizationDlgSettings {
            get {
                return ((string)(this["LocalizationDlgSettings"]));
            }
            set {
                this["LocalizationDlgSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public int MillisecondsToDelayPlaybackAfterAdjustingSegmentBoundary {
            get {
                return ((int)(this["MillisecondsToDelayPlaybackAfterAdjustingSegmentBoundary"]));
            }
            set {
                this["MillisecondsToDelayPlaybackAfterAdjustingSegmentBoundary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public float ZoomPercentageInAnnotationRecordingDlg {
            get {
                return ((float)(this["ZoomPercentageInAnnotationRecordingDlg"]));
            }
            set {
                this["ZoomPercentageInAnnotationRecordingDlg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SilTools.FormSettings ManualSegmenterDlg {
            get {
                return ((global::SilTools.FormSettings)(this["ManualSegmenterDlg"]));
            }
            set {
                this["ManualSegmenterDlg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public float ZoomPercentageInManualSegmenterDlg {
            get {
                return ((float)(this["ZoomPercentageInManualSegmenterDlg"]));
            }
            set {
                this["ZoomPercentageInManualSegmenterDlg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int DefaultSegmentationMethod {
            get {
                return ((int)(this["DefaultSegmentationMethod"]));
            }
            set {
                this["DefaultSegmentationMethod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilTools.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1250")]
        public int MinimumAnnotationSegmentLengthInMilliseconds {
            get {
                return ((int)(this["MinimumAnnotationSegmentLengthInMilliseconds"]));
            }
            set {
                this["MinimumAnnotationSegmentLengthInMilliseconds"] = value;
            }
        }
    }
}
