//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SayMore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SayMore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream finished {
            get {
                return ResourceManager.GetStream("finished", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap kimidBrowseForProject {
            get {
                object obj = ResourceManager.GetObject("kimidBrowseForProject", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidChangePicture {
            get {
                object obj = ResourceManager.GetObject("kimidChangePicture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidChangeProject {
            get {
                object obj = ResourceManager.GetObject("kimidChangeProject", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidFemale_NotSelected {
            get {
                object obj = ResourceManager.GetObject("kimidFemale_NotSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidFemale_Selected {
            get {
                object obj = ResourceManager.GetObject("kimidFemale_Selected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidMale_NotSelected {
            get {
                object obj = ResourceManager.GetObject("kimidMale_NotSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidMale_Selected {
            get {
                object obj = ResourceManager.GetObject("kimidMale_Selected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidMoreAction {
            get {
                object obj = ResourceManager.GetObject("kimidMoreAction", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidNewProject {
            get {
                object obj = ResourceManager.GetObject("kimidNewProject", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidNoPermissionsWarning {
            get {
                object obj = ResourceManager.GetObject("kimidNoPermissionsWarning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidNoPhoto {
            get {
                object obj = ResourceManager.GetObject("kimidNoPhoto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidOverview {
            get {
                object obj = ResourceManager.GetObject("kimidOverview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidPeople {
            get {
                object obj = ResourceManager.GetObject("kimidPeople", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidSendReceive {
            get {
                object obj = ResourceManager.GetObject("kimidSendReceive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidSessions {
            get {
                object obj = ResourceManager.GetObject("kimidSessions", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidSetup {
            get {
                object obj = ResourceManager.GetObject("kimidSetup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidSponge {
            get {
                object obj = ResourceManager.GetObject("kimidSponge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidSpongeSmall {
            get {
                object obj = ResourceManager.GetObject("kimidSpongeSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidSpongeText {
            get {
                object obj = ResourceManager.GetObject("kimidSpongeText", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kimidWarning {
            get {
                object obj = ResourceManager.GetObject("kimidWarning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon Sponge {
            get {
                object obj = ResourceManager.GetObject("Sponge", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static object wmpOcxState {
            get {
                object obj = ResourceManager.GetObject("wmpOcxState", resourceCulture);
                return ((object)(obj));
            }
        }
    }
}
