//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sponge2.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection MRUList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MRUList"]));
            }
            set {
                this["MRUList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int LocalizationDlgSplitterPos {
            get {
                return ((int)(this["LocalizationDlgSplitterPos"]));
            }
            set {
                this["LocalizationDlgSplitterPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 0, -1")]
        public global::System.Drawing.Rectangle LocalizationDlgBounds {
            get {
                return ((global::System.Drawing.Rectangle)(this["LocalizationDlgBounds"]));
            }
            set {
                this["LocalizationDlgBounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 0, -1")]
        public global::System.Drawing.Rectangle ProjectWindowBounds {
            get {
                return ((global::System.Drawing.Rectangle)(this["ProjectWindowBounds"]));
            }
            set {
                this["ProjectWindowBounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 0, -1")]
        public global::System.Drawing.Rectangle WelcomeDialogBounds {
            get {
                return ((global::System.Drawing.Rectangle)(this["WelcomeDialogBounds"]));
            }
            set {
                this["WelcomeDialogBounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int SessionVwSplitterPos {
            get {
                return ((int)(this["SessionVwSplitterPos"]));
            }
            set {
                this["SessionVwSplitterPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string SessionFileCols {
            get {
                return ((string)(this["SessionFileCols"]));
            }
            set {
                this["SessionFileCols"] = value;
            }
        }
        
        /// <summary>
        /// Character used to replace invalid path characters in a person&apos;s name when building a safe name to store in file system.
        /// </summary>
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Character used to replace invalid path characters in a person\'s name when buildin" +
            "g a safe name to store in file system.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_")]
        public char SafeNameReplacementChar {
            get {
                return ((char)(this["SafeNameReplacementChar"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("207, 240, 159")]
        public global::System.Drawing.Color DataEntryPanelColorBegin {
            get {
                return ((global::System.Drawing.Color)(this["DataEntryPanelColorBegin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("169, 219, 168")]
        public global::System.Drawing.Color DataEntryPanelColorEnd {
            get {
                return ((global::System.Drawing.Color)(this["DataEntryPanelColorEnd"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("148, 195, 151")]
        public global::System.Drawing.Color DataEntryPanelColorBorder {
            get {
                return ((global::System.Drawing.Color)(this["DataEntryPanelColorBorder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("196, 209, 227")]
        public global::System.Drawing.Color BarColorBegin {
            get {
                return ((global::System.Drawing.Color)(this["BarColorBegin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("124, 153, 193")]
        public global::System.Drawing.Color BarColorEnd {
            get {
                return ((global::System.Drawing.Color)(this["BarColorEnd"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("83, 110, 145")]
        public global::System.Drawing.Color BarColorBorder {
            get {
                return ((global::System.Drawing.Color)(this["BarColorBorder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int GapBetweenMultimediaObjects {
            get {
                return ((int)(this["GapBetweenMultimediaObjects"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int DefaultHeightOfVideoControl {
            get {
                return ((int)(this["DefaultHeightOfVideoControl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("65")]
        public int DefaultHeightOfAudioControl {
            get {
                return ((int)(this["DefaultHeightOfAudioControl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int DefaultHeightOfImageControl {
            get {
                return ((int)(this["DefaultHeightOfImageControl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".mp3, .wav, .wma, .acc, .ogg")]
        public string AudioFileExtensions {
            get {
                return ((string)(this["AudioFileExtensions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".wmv, .avi, .mpg, .mpeg, .mpa, .asf, .mov")]
        public string VideoFileExtensions {
            get {
                return ((string)(this["VideoFileExtensions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".jpg, .jpeg, .gif, .tif, .png, .bmp, .dib")]
        public string ImageFileExtensions {
            get {
                return ((string)(this["ImageFileExtensions"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RedrawAsMainWndResizes {
            get {
                return ((bool)(this["RedrawAsMainWndResizes"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 0, -1")]
        public global::System.Drawing.Rectangle NewSessionsFromFilesDlgBounds {
            get {
                return ((global::System.Drawing.Rectangle)(this["NewSessionsFromFilesDlgBounds"]));
            }
            set {
                this["NewSessionsFromFilesDlgBounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string NewSessionsFromFilesDlgCols {
            get {
                return ((string)(this["NewSessionsFromFilesDlgCols"]));
            }
            set {
                this["NewSessionsFromFilesDlgCols"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string NewSessionsFromFilesLastFolder {
            get {
                return ((string)(this["NewSessionsFromFilesLastFolder"]));
            }
            set {
                this["NewSessionsFromFilesLastFolder"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("www.sil.org")]
        public string SilWebSite {
            get {
                return ((string)(this["SilWebSite"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("www.spongetheband.com")]
        public string ProgramsWebSite {
            get {
                return ((string)(this["ProgramsWebSite"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int PersonScreenElementListSpiltterPos {
            get {
                return ((int)(this["PersonScreenElementListSpiltterPos"]));
            }
            set {
                this["PersonScreenElementListSpiltterPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int PersonScreenComponentsSplitterPos {
            get {
                return ((int)(this["PersonScreenComponentsSplitterPos"]));
            }
            set {
                this["PersonScreenComponentsSplitterPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int SessionsScreenElementsListSplitterPos {
            get {
                return ((int)(this["SessionsScreenElementsListSplitterPos"]));
            }
            set {
                this["SessionsScreenElementsListSplitterPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(SilUtils.PortableSettingsProvider))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int SessionsScreenComponentsSplitterPos {
            get {
                return ((int)(this["SessionsScreenComponentsSplitterPos"]));
            }
            set {
                this["SessionsScreenComponentsSplitterPos"] = value;
            }
        }
    }
}
