name: Windows Build

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

env:
  Configuration: Release
  BUILD_NUMBER: 3.7.${{ github.run_number }}.${{ github.sha }}

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore NuGet packages
        run: nuget restore SayMore.sln

      - name: Fetch native dependencies
        shell: bash
        run: ./getDependencies.sh

      - name: Fetch documentation artifacts
        shell: bash
        run: build/getDependencies-windows.sh

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: '[17.0,18.0)'

      - name: Build solution
        run: msbuild build\SayMore.proj /t:Build /p:Configuration=$env:Configuration /p:useNUnit-x86=true /m

      - name: Run tests
        run: msbuild build\SayMore.proj /t:Test /p:Configuration=$env:Configuration /p:useNUnit-x86=true /p:excludedCategories=SkipOnTeamCity /m

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: saymore-windows
          if-no-files-found: warn
          path: |
            output/${{ env.Configuration }}/TestResults.xml
